### ISSUE TITLE
Buckets Cannot Be Created - Using docker-compose.yml

### ISSUE THREAD

**Issue by amols-webonise** [ianbytchek/docker-riak-cs#12]
==========docker-compose.yml=============
riak-cs:
    image: ianbytchek/riak-cs
    container_name: riak-cs-amazon-s3
    healthcheck:
      timeout: 60s
      retries: 10 
    environment:
      - RIAK_CS_BUCKETS=riak
      - RIAK_CS_KEY_ACCESS=CC2QOJQ4VJFR8USBS5Y3
      - RIAK_CS_KEY_SECRET=dKoX0b8dKbSFS0lJ_euHAVdgHMPDuB9GDZgJ8Q==
    ports:
      - "8080:8080"

========docker logs===========
riak-cs-amazon-s3 | Waiting for riak kv service to startup… OK!
riak-cs-amazon-s3 | Starting Stanchion… OK!
riak-cs-amazon-s3 | Starting Riak CS… OK!
riak-cs-amazon-s3 | 
riak-cs-amazon-s3 | ############################################################
riak-cs-amazon-s3 | 
riak-cs-amazon-s3 |     Riak admin credentials, make note of them, otherwise you
riak-cs-amazon-s3 |     will not be able to access your files and data. Riak
riak-cs-amazon-s3 |     services will be restarted to take effect.
riak-cs-amazon-s3 | 
riak-cs-amazon-s3 |     Access key: CC2QOJQ4VJFR8USBS5Y3
riak-cs-amazon-s3 |     Secret key: dKoX0b8dKbSFS0lJ_euHAVdgHMPDuB9GDZgJ8Q==
riak-cs-amazon-s3 | 
riak-cs-amazon-s3 | ############################################################
riak-cs-amazon-s3 | 
riak-cs-amazon-s3 | Restarting Riak… OK!
riak-cs-amazon-s3 | Waiting for riak kv service to startup… OK!
riak-cs-amazon-s3 | Restarting Stanchion…Restarting Riak CS…Node 'riak-cs@127.0.0.1' not responding to pings.
riak-cs-amazon-s3 | Node 'riak-cs@127.0.0.1' not responding to pings.
riak-cs-amazon-s3 |  OK!
riak-cs-amazon-s3 | Creating Riak CS buckets.
riak-cs-amazon-s3 | riak… Failed!
riak-cs-amazon-s3 | 2018-02-19 09:35:48,371 CRIT Supervisor running as root (no user in config file)
riak-cs-amazon-s3 | 2018-02-19 09:35:48,371 WARN Included extra file "/entrypoint/configuration/supervisord/stanchion.conf" during parsing
riak-cs-amazon-s3 | 2018-02-19 09:35:48,371 WARN Included extra file "/entrypoint/configuration/supervisord/riak-cs.conf" during parsing
riak-cs-amazon-s3 | 2018-02-19 09:35:48,371 WARN Included extra file "/entrypoint/configuration/supervisord/riak.conf" during parsing
riak-cs-amazon-s3 | 2018-02-19 09:35:48,374 INFO supervisord started with pid 4906
riak-cs-amazon-s3 | 2018-02-19 09:35:49,376 INFO spawned: 'riak' with pid 4909
riak-cs-amazon-s3 | 2018-02-19 09:35:49,378 INFO spawned: 'stanchion' with pid 4910
riak-cs-amazon-s3 | 2018-02-19 09:35:49,380 INFO spawned: 'riak-cs' with pid 4911
riak-cs-amazon-s3 | 2018-02-19 09:35:49,839 INFO exited: riak-cs (exit status 1; not expected)
riak-cs-amazon-s3 | 2018-02-19 09:35:49,859 INFO exited: stanchion (exit status 1; not expected)
riak-cs-amazon-s3 | 2018-02-19 09:35:51,001 INFO success: riak entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
riak-cs-amazon-s3 | 2018-02-19 09:35:51,007 INFO spawned: 'stanchion' with pid 5248
riak-cs-amazon-s3 | 2018-02-19 09:35:51,013 INFO spawned: 'riak-cs' with pid 5249
riak-cs-amazon-s3 | 2018-02-19 09:35:51,440 INFO exited: stanchion (exit status 1; not expected)
riak-cs-amazon-s3 | 2018-02-19 09:35:51,492 INFO exited: riak-cs (exit status 1; not expected)
riak-cs-amazon-s3 | 2018-02-19 09:35:53,494 INFO spawned: 'stanchion' with pid 5454
riak-cs-amazon-s3 | 2018-02-19 09:35:53,496 INFO spawned: 'riak-cs' with pid 5455
riak-cs-amazon-s3 | 2018-02-19 09:35:53,860 INFO exited: stanchion (exit status 1; not expected)
riak-cs-amazon-s3 | 2018-02-19 09:35:53,874 INFO exited: riak-cs (exit status 1; not expected)
riak-cs-amazon-s3 | 2018-02-19 09:35:56,878 INFO spawned: 'stanchion' with pid 5660
riak-cs-amazon-s3 | 2018-02-19 09:35:56,879 INFO spawned: 'riak-cs' with pid 5661
riak-cs-amazon-s3 | 2018-02-19 09:35:57,254 INFO exited: stanchion (exit status 1; not expected)
riak-cs-amazon-s3 | 2018-02-19 09:35:57,256 INFO gave up: stanchion entered FATAL state, too many start retries too quickly
riak-cs-amazon-s3 | 2018-02-19 09:35:57,256 INFO exited: riak-cs (exit status 1; not expected)
riak-cs-amazon-s3 | 2018-02-19 09:35:58,257 INFO gave up: riak-cs entered FATAL state, too many start retries too quickly

**Comment by iby** [comment]
Did you read carefully about [configuration](https://github.com/ianbytchek/docker-riak-cs#configuration) keys, this part in particular:

> Only use this with a mounted data volume when your data is already created and there is already a user with this credentials. Otherwise the default admin user will not be created and you'll get an error.

Is there an existing volume with data and configured credentials?

**Comment by amols-webonise** [comment]
I don't have it. But, I need a configuration with fixed bucket with fixed credentials.

**Comment by iby** [comment]
Two options. First, create volume with autogenerated credentials, then simply connect it and use like you're doing above. Second, extract credentials like [test.sh](https://github.com/ianbytchek/docker-riak-cs/blob/55aef0d0eafa81ccc72ff3b2d5aa81a15ee99b6d/build/ci/script/test.sh#L34-L35) does. Unfortunately, inability to pass credentials from the start is how Riak works and done for security reasons beyond my comprehension.

**Comment by amols-webonise** [comment]
@ianbytchek can you tell me where the volume will be mounted? and also should i change /etc/riak-cs/advanced.config and provide it with my generated key access and key secret?

**Comment by iby** [comment]
I'd be happy to help, but haven't practiced Docker for a while – you'd be better off with googling that yourself, sorry. Check out #6 for more details on volumes. I couldn't get it to work on macOS back then, but @lksv had more luck on Linux. You can chase this with him, see if he remembers anything. But if you only want an S3 testing server I'd recommend googling that too – there are many simpler alternatives. I haven't tried any, but pretty sure the state of things is 💯 times better than 2 years ago.
