### ISSUE TITLE
Expose Riak control UI ?

### ISSUE THREAD

**Issue by VAdamec** [ianbytchek/docker-riak-cs#9]
Should be on default port 8098, no luck to find correct config parameter to listen on ip not loopback (versions?) http://docs.basho.com/riak/kv/2.2.0/using/admin/riak-control/

**Comment by iby** [comment]
Hey, sorry, I'm not actively maintaining this project at the moment, but happy to guide through if you want to make improvements. As far as I remember Riak Control was never enabled from looking at the docs. I haven't used Riak in depth for awhile, so might be confusing something, but it seems Riak Control would be a little useless for Riak CS and this project in particular. This image was built solely to provide S3 testing environment in a single node setup and I wouldn't recommend it for anything else. There's [hectcastro/docker-riak-cs](https://github.com/hectcastro/docker-riak-cs) repo maintained by one of Basho's developers, which allows multiple nodes, if I remember correctly there are a few other Riak-specific projects out there. If you feel Riak Control would be useful here and happy to send a PR, let me know, I'll help with what I can.

**Comment by iby** [comment]
I'm gonna close this, feel free to reopen if you have further comments.
